ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: false      # fast_slam will handle the map->odom TF
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # --- INPUT 1: WHEEL ODOMETRY ---
    odom0: /diff_cont/odom
    odom0_config: [false, false, false,  # X, Y, Z (Don't fuse Pose X/Y, let EKF integrate velocity)
                   false, false, false,  # R, P, Yaw (IGNORE WHEEL ROTATION)
                   true,  false, false,  # VX, VY, VZ (Trust Wheel Speed)
                   false, false, true,   # VRoll, VPitch, VYaw (Trust Wheel Turn Speed?)
                   false, false, false]  # Accel
    odom0_differential: false

    # --- INPUT 2: IMU ---
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,   # Trust IMU Yaw (Orientation)
                  false, false, false,
                  false, false, true,   # Trust IMU Yaw Velocity
                  true,  false, false]  # Trust IMU Accel (helps start/stop)
    imu0_differential: false