controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link

    # Use vertical list for maximum safety
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']

    wheel_separation: 0.55
    wheel_radius: 0.075
    enable_odom_tf: true
    use_stamped_vel: false